### ISSUE TITLE
Migrate stack to nodejs

### ISSUE THREAD

**Issue by Kkevsterrr** [bekher/synesthesia-web#9]
I think actually our entire stack can be migrated to nodejs...
It's basically:
.MP3 -> .wav (can be done w/ https://www.npmjs.com/package/sox)
.wav -> .raw (can also likely be done w/ sox)
.raw -> .png (can hopefully be done with jimp - https://www.npmjs.com/package/jimp)
transformations (node-png - https://www.npmjs.com/package/node-png)
and then back up... what are your thoughts? Would definitely make it faster, a lot quicker to stand up, and better integrated!

**Comment by bekher** [comment]
That's a great idea for the transformations, since it will greatly increase portability. However, wouldn't we want to keep the transformation logic in Python?

**Comment by Kkevsterrr** [comment]
No actually! The node-png gives us the exact same control over the data as does the python libraries, and the code could easily be ported!
